import type { Metadata } from "next";
import "./globals.css";
import styles from "./layout.module.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <nav className={styles.nav}>
          <ul>
            <Link href="/" legacyBehavior><a>HomeApp</a></Link>
            <Link href="/cooks" legacyBehavior><a>料理トップへ</a></Link>
          </ul>
        </nav>


        <div className={styles.baseLayout}>{children}</div>
      </body>
    </html>
  );
}
